### ISSUE TITLE
Search integration

### ISSUE THREAD

**Issue by digitalcraftsman** [sjardim/docs.gohugo.io#4]
Hello @sjardim,

in the [forum discussion](https://discuss.gohugo.io/t/new-theme-for-hugo-docs-http-hugodocs-netlify-com/2335) about your redesign you mentioned Algolia as a search provider. They offer their service [ docsearch](http://community.algolia.com/docsearch/) for free to open source projects. They also show the integration of their service in existing projects.

I've taken the liberty to contact folks at Algolia and asked if they would adjust their crawler for your current demo site and they did. This is only meant as a prototype and in my opion as a better alternative as Google CSE.

Furthermore, I don't know how @spf13 thinks about the integration of a third-party service like this, but it works great so far.

An integration can be found [here](https://github.com/digitalcraftsman/docs.gohugo.io/tree/search-algolia). Alternatively, I made a quick [screencast](http://sendvid.com/sgxrr49x).

---
- [ ] Add Hugo to the [example page](http://community.algolia.com/docsearch/) of Algolia

**Comment by sjardim** [comment]
Hi @digitalcraftsman! 

The search seems incredible! Thank you very much for this and also for the 3 PR's you've sent already. :+1: 

I think @spf13 will love it! :)

I'm taking some days off ("vacation") and as soon as a I go back (one week +/- ) I give it a more in-depth look, ok?

All the best,
Sergio

**Comment by digitalcraftsman** [comment]
> I'm taking some days off ("vacation") and as soon as a I go back (one week +/- ) I give it a more in-depth look, ok?

Take your time. We don't need to rush. Once you find time, we could adjust the default styling of the search to match the theme a bit more.

**Comment by spf13** [comment]
I fully support anything that will make the hugo experience better. We already have 3rd party with Google. I don't see how this is any different.

**Comment by ElPicador** [comment]
Allow me to jump in. 
I'm the one who did the Algolia DocSearch on the documentation of hugo.
For the difference between Google web search and Algolia's, here is 2 GIFs.
- Google
  ![Google](http://g.recordit.co/lGfdS8LKTP.gif)
- Algolia
  ![Algolia](http://g.recordit.co/4IqvEe9x8t.gif)

I think they speak for themselves :smile:

**Comment by spf13** [comment]
Agreed. Let's do it. Algolia FTW.
